spring:
   h2:
      console:
         enabled: true
   jpa:
      hibernate.ddl-auto: create-drop
      show-sql: true
      
   datasource:
      url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driverClassName: org.h2.Driver